use_frameworks!

platform :ios, '9.0'

target 'JDYYPodTest_Example' do
  pod 'JDYYPodTest', :path => '../'

  target 'JDYYPodTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
